# Generated by Django 6.0.5 on 2026-07-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
